### ISSUE TITLE
[Friendship issue - no friends are showing]

### ISSUE THREAD

**Issue by rvvergara** [gferrarocamus/building-facebook#10]
Like in previous tests in the console, I created `ryto` and `mike`. Then I ran:

`ryto.active_friendships.create(passive_friend_id: mike.id)`.

And yeah after that, running `Friendship.all` indeed just made 1 record (great!).

However, when I ran:

`ryto.friends` -> `[ ]`
`mike.friends` -> `[ ]`
`ryto.active_friends` and `ryto.passive_friends` -> both empty
`mike.active_friends` and `mike.passive_friends` -> both empty

**Comment by gferrarocamus** [comment]
Hi, @rvvergara,

We're unable to replicate this issue. The association seems to be working, while keeping the `inverse_of` line [as required](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/InverseOf) by the linter, Rubocop. 

Could you review this again or tell us how to replicate the issue?

Thanks!

**Comment by rvvergara** [comment]
To replicate:

1. Create 2 users -> ryto and mike
2. Run `ryto.active_friendships.create(passive_friend_id: mike.id)`
3. Run `ryto.friends` and `mike.friends` and check for the results

Now it appears to be working. I cannot point to the cause of the previous bug but after pulling your latest changes (previously I couldn't run `pry-rails` and `hirb` successfully in the console) it's now working :)
